services:
  - type: web
    name: face-emotion-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app  # Defaults to 8000
    plan: free
    envVars:
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2