services:
  - type: web
    name: face-emotion-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    plan: free
    envVars:
      - key: PORT
        value: 5000
