services:
  - type: web
    name: face-emotion-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: TF_CPP_MIN_LOG_LEVEL  # Add this to suppress the TensorRT warning
        value: 2                   # 2 hides INFO and WARNING messages
      # Add other environment variables here if needed
      # - key: NAME_OF_VARIABLE
      #   value: value